"""add overdue field in task

Revision ID: 13eec715dc1f
Revises: cc29d67ae41b
Create Date: 2025-10-06 13:43:07.112846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13eec715dc1f'
down_revision = 'cc29d67ae41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overdue', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('overdue')

    # ### end Alembic commands ###
