"""add new fields in Task Model

Revision ID: cc29d67ae41b
Revises: ce986d246e7a
Create Date: 2025-10-05 17:48:27.782761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc29d67ae41b'
down_revision = 'ce986d246e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=False, server_default=sa.text("'00:00:00'")))
        batch_op.add_column(sa.Column('finish_time', sa.Time(), nullable=False,  server_default=sa.text("'00:00:00'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('finish_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
